---
title: "thebrenniacs"
author: "The Brenniacs"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(here)
```

```{r}
# read in the data from /courses/EDS214/group_project/thebrenniacs/data

bq1 <- read_csv(here("/courses/EDS214/group_project/thebrenniacs/data", "BQ1.csv"))

bq2 <- read_csv(here("/courses/EDS214/group_project/thebrenniacs/data", "BQ2.csv"))

bq3 <- read_csv(here("/courses/EDS214/group_project/thebrenniacs/data", "BQ3.csv"))

prm <- read_csv(here("/courses/EDS214/group_project/thebrenniacs/data", "PRM.csv"))

```

```{r}
watershed_areas <- bq1 %>% 
  bind_rows(bq2) %>% 
  bind_rows(bq3) %>% 
  bind_rows(prm)
```

```{r}
# check the data integrity across the datasets
# total number of columns is the same
# columns are in the same order
bq1_vec <- names(bq1)
bq2_vec <- names(bq2)
bq3_vec <- names(bq3)
prm_vec <- names(prm)

compare_columns <- data.frame(bq1 = bq1_vec, 
                              bq2 = bq2_vec,
                              bq3 = bq3_vec,
                              prm = prm_vec)

compare_columns$check = ifelse((compare_columns$bq1 == compare_columns$bq2) 
                               & (compare_columns$bq2 == compare_columns$bq3)
                               & (compare_columns$bq3 == compare_columns$prm),
                               "Same", "Diff")

view(compare_columns)
```

```{r}
# Data Wrangling
library(zoo)
# convert dates
watershed_areas_summary <- watershed_areas %>% 
  #Convert all dates into ISO8601 format
  mutate(Sample_Date = lubridate::ymd(watershed_areas$Sample_Date)) %>% 
  #Create a new column "Period = Year-Month"
  mutate(Period = zoo::as.yearmon(Sample_Date)) %>% 
  relocate(Period, .after = Sample_Date) %>% 
  select(-Code, -Sample_Time) %>% 
  group_by(Sample_ID, Period) %>% 
  summarise(across(where(is.numeric), 
                   list(mean = mean,
                        sd = sd,
                        max = max,
                        min = min),
                   na.rm = TRUE,
                   .names = "{col}_{.fn}"))
```

```{r}
watershed_areas_NO3N_plot <- watershed_areas_summary %>% 
  select(Sample_ID, Period, "NO3-N_mean", "NO3-N_max", "NO3-N_sd") %>% 
  drop_na() %>% 
  rename(no3nmean = "NO3-N_mean",
         no3nmax = "NO3-N_max",
         no3nsd = "NO3-N_sd",
         period = Period) %>% 
  ggplot(aes(x = period,
             y = no3nmean))+
  geom_line(aes(color = Sample_ID))+
  scale_x_continuous(limits = c(1986, 2020), 
                     breaks = seq(from = 1986, to = 2020, by = 3),
                     expand = c(0, 0))+
  annotate("text",
           label = "Hugo, Sep'1989",
           angle = 90,
           x = 1989,
           y = 500,
           size = 3)+
    annotate("text",
           label = "Georges, Sep'1998",
           angle = 90,
           x = 1998,
           y = 500,
           size = 3)+
    annotate("text",
           label = "María, Sep'2017",
           angle = 90,
           x = 2017,
           y = 500,
           size = 3)+
  theme_minimal()

watershed_areas_NO3N_plot


```

-   Hurricane Hugo: Sep 9, 1989 -- Sep 25, 1989
-   Hurricane Georges: Sep 15, 1998 -- Oct 1, 1998
-   Hurricane María: Sep 16, 2017 -- Oct 2, 2017

```{r}
library(scales)
library(patchwork)

watershed_areas_chemistry <- watershed_areas %>% 
  select(Sample_ID, Sample_Date, K, `NO3-N`) %>%
  drop_na()

# Potassium level 
level_K <- ggplot(data = watershed_areas_chemistry, 
                  aes(x = Sample_Date, y = K, color = Sample_ID)) +
  geom_line() +
  labs(x = "Period", y = "K+ (mg/l)") +
  scale_x_date(breaks = seq(as.Date("1988-01-01"),
                            as.Date("1995-01-01"),
                            by = "1 year"),
               limits = c(as.Date("1988-01-01"), as.Date("1995-01-01")),
               expand = c(0, 0),
               labels = date_format("%Y")) +  # Format tick labels as year only
  theme_minimal()

# Nitrate Nitrogen level 
level_NO3N <- ggplot(data = watershed_areas_chemistry, 
                     aes(x = Sample_Date, y = `NO3-N`, color = Sample_ID)) +
  geom_line() +
  labs(x = "Period", y = "NO3-N (ug/l)") +
  scale_x_date(breaks = seq(as.Date("1988-01-01"),
                            as.Date("1995-01-01"),
                            by = "1 year"),
               limits = c(as.Date("1988-01-01"), as.Date("1995-01-01")),
               expand = c(0, 0),
               labels = date_format("%Y"))+
  theme_minimal()

p_no3n_k <- ((level_K / level_NO3N))
ggsave(here::here("figs","no3n_k_combined.png" ), p_no3n_k)
```

```{r}

##plotting ion concentrations (Na, K, Ca, Mg) against conductivity for all samples (sites + times) to explore the relationship between the two variables## 
p1_Ca_cond <- ggplot(watershed_areas, aes(x=Ca, y=Cond, color = Sample_ID))+geom_point(alpha = 0.2)+ylim(min=0, max=250) + geom_smooth(method = "lm", se = FALSE) + ylab("Cond. (mS/cm)") + xlab("Concn of Ca (mg/L)") +   theme(legend.position="none")

p2_Na_cond <- ggplot(watershed_areas, aes(x=Na, y=Cond, color = Sample_ID))+geom_point(alpha = 0.2)+ylim(min=0, max=250) + geom_smooth(method = "lm", se = FALSE) + ylab("Cond. (mS/cm)") +  xlab("Concn of Na (mg/L)") 

p3_Mg_cond <- ggplot(watershed_areas, aes(x=Mg, y=Cond, color = Sample_ID))+geom_point(alpha = 0.2)+ylim(min=0, max=250) + geom_smooth(method = "lm", se = FALSE)+  ylab("Cond. (mS/cm)") + xlab("Concn of Mg (mg/L)")  +   theme(legend.position="none") 

p4_K_cond <- ggplot(watershed_areas, aes(x=K, y=Cond, color = Sample_ID))+geom_point(alpha = 0.2)+ylim(min=0, max=250) + geom_smooth(method = "lm", se = FALSE) +  ylab("Cond. (mS/cm)") + xlab("Concn of K (ug/L)")  +   theme(legend.position="none") 

p <- (p1_Ca_cond | p2_Na_cond)/(p3_Mg_cond|p4_K_cond) + plot_annotation('Largely Positive Correl. between Conductivity & Ion Concentrations across Sites*', caption = '* All but BQ1, for K',theme=theme(plot.title=element_text(hjust=0.5))) 

ggsave(here::here("figs","conductivity.png" ), p)


##explanation. 


```

```{r}
# Explore the impact of hurricanes on pH level in rivers
smooth_data<- watershed_areas %>%
  mutate(year= format(Sample_Date, format = "%Y")) %>%
  filter(year> 2006 , year< 2014)
ph <- ggplot(data = watershed_areas,
                     aes(y = pH, x = Sample_Date)) +
  scale_x_date(breaks = seq(as.Date("1986-01-01"),
                            as.Date("2019-01-01"),
                            by = "5 year"),
               limits = c(as.Date("1986-01-01"), as.Date("2019-01-01")),
               expand = c(0, 0),
               labels = date_format("%Y"))+
  geom_line(aes(color = Sample_ID))+
  geom_smooth(data= smooth_data, method = "lm")

p_ph <- (( watershed_areas_NO3N_plot / ph))

ggsave(here::here("figs","pH_level_timeseries.png" ), p_ph)
```
